apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
  namespace: billing
data:
  PORT: "3001"
  NODE_ENV: "production"
  DB_PORT: "5432"
  NEW_RELIC_APP_NAME: "autoflow-billing"
  NEW_RELIC_ENABLED: "false"
