apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
  namespace: billing
  labels:
    app: billing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
        - name: billing
          image: kaikelfalcao/autoflow-billing:latest
          ports:
            - containerPort: 3001
          envFrom:
            - secretRef:
                name: billing-secrets
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /billing/health/liveness
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /billing/health/readiness
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
